// Demo data for Egyptian Padel & Football Booking Platform in Upper Egypt (Assiut, Sohag & Upper Egypt)

export const EGYPT_CITIES = [
  { id: 'all', en: 'All Upper Egypt', ar: 'جميع مدن الصعيد' },
  { id: 'assiut', en: 'Assiut (أسيوط)', ar: 'أسيوط' },
  { id: 'sohag', en: 'Sohag (سوهاج)', ar: 'سوهاج' },
  { id: 'minya', en: 'Minya (المنيا)', ar: 'المنيا' },
  { id: 'qena', en: 'Qena & Luxor (قنا والأقصر)', ar: 'قنا والأقصر' },
  { id: 'aswan', en: 'Aswan (أسوان)', ar: 'أسوان' },
];

export const COURT_TYPES = [
  { id: 'all', en: 'All Sports & Courts', ar: 'جميع الملاعب' },
  { id: 'padel', en: 'Padel Courts', ar: 'ملاعب باديل' },
  { id: 'football', en: 'Football 5v5/7v7', ar: 'ملاعب كرة قدم' },
  { id: 'indoor', en: 'Covered AC', ar: 'مغطى ومكيف' },
];

export const DEMO_COURTS = [
  {
    id: 'court-1',
    nameEn: 'Padel Square Assiut',
    nameAr: 'بادل سكوير أسيوط',
    cityId: 'assiut',
    sportType: 'padel',
    locationEn: 'Nile Corniche, Assiut City',
    locationAr: 'أسيوط • كورنيش النيل بجوار النادي الرياضي',
    rating: 4.9,
    reviewsCount: 184,
    pricePerHour: 350, // EGP
    type: 'padel',
    typeEn: 'Outdoor Panoramic Padel',
    typeAr: 'باديل بانورامي خارجي',
    surfaceEn: 'Mondo Supercourt X3 (Blue)',
    surfaceAr: 'نجيل موندو سوبر كورت أزرق',
    image: 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?auto=format&fit=crop&q=80&w=1000',
    facilities: ['Parking', 'AC Lounge', 'Shower Rooms', 'Pro Rackets', 'Cafe'],
    facilitiesAr: ['موقف سيارات', 'استراحة مكيفة', 'غرف دش', 'مضارب احترافية', 'كافيه'],
    badgeEn: 'Popular Padel in Assiut',
    badgeAr: 'الأكثر حجزاً بأسيوط',
    availableSlotAr: '07:30 م شاغر',
    availableSlots: ['5:30 PM', '7:00 PM', '8:30 PM', '10:00 PM'],
  },
  {
    id: 'court-2',
    nameEn: 'Sohag Football Arena 5v5',
    nameAr: 'ملعب خماسي سوهاج الرياضي',
    cityId: 'sohag',
    sportType: 'football',
    locationEn: 'Al-Kawtar District, Sohag',
    locationAr: 'سوهاج • حي الكوثر الرئيسي',
    rating: 4.9,
    reviewsCount: 230,
    pricePerHour: 280,
    type: 'football',
    typeEn: '5v5 Premium Turf Football',
    typeAr: 'كرة قدم خماسي نجيل هولندي',
    surfaceEn: 'Dutch FIFA Certified Turf 50mm',
    surfaceAr: 'نجيل هولندي معتمد FIFA',
    image: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&q=80&w=1000',
    facilities: ['LED Night Lighting', 'Match Video HD', 'Locker Rooms', 'Cafeteria'],
    facilitiesAr: ['إضاءة ليلية كشافات LED', 'تصوير ماتشات HD', 'غرف تغيير ملابس', 'كافتيريا'],
    badgeEn: 'Top Football Turf',
    badgeAr: 'أفضل ملعب خماسي بسوهاج',
    availableSlotAr: '08:30 م شاغر',
    availableSlots: ['6:00 PM', '7:30 PM', '9:00 PM', '10:30 PM'],
  },
  {
    id: 'court-3',
    nameEn: 'Padel Club Sohag',
    nameAr: 'بادل كلوب سوهاج',
    cityId: 'sohag',
    sportType: 'padel',
    locationEn: 'Eastern District, Sohag City',
    locationAr: 'سوهاج • الحي الشرقي بجوار الاستاد',
    rating: 4.8,
    reviewsCount: 140,
    pricePerHour: 320,
    type: 'padel',
    typeEn: 'Outdoor Glass Padel',
    typeAr: 'باديل بانوراما خارجي',
    surfaceEn: 'Blue Pro Padel Turf',
    surfaceAr: 'نجيل أزرق احترافي للباديل',
    image: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&q=80&w=1000',
    facilities: ['VIP Lounge', 'Match Recording', 'Free Rackets'],
    facilitiesAr: ['استراحة VIP', 'تسجيل فيديو للماتش', 'مضارب مجانية'],
    badgeEn: '#1 Padel Sohag',
    badgeAr: 'أول ملعب باديل بسوهاج',
    availableSlotAr: '09:00 م شاغر',
    availableSlots: ['5:00 PM', '6:30 PM', '8:00 PM', '9:30 PM'],
  },
  {
    id: 'court-4',
    nameEn: 'Assiut University Football 7v7',
    nameAr: 'ملعب سباعي جامعة أسيوط',
    cityId: 'assiut',
    sportType: 'football',
    locationEn: 'University District, Assiut',
    locationAr: 'أسيوط • شارع الجامعة الرئيسي',
    rating: 4.8,
    reviewsCount: 310,
    pricePerHour: 350,
    type: 'football',
    typeEn: '7v7 Large Football Field',
    typeAr: 'كرة قدم سباعي مساحة كبيرة',
    surfaceEn: 'Monofilament Turf 60mm',
    surfaceAr: 'نجيل أحادي الفتيل 60 مم',
    image: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&q=80&w=1000',
    facilities: ['Tribunes 200 Seats', 'Changing Rooms', 'Water Refreshments'],
    facilitiesAr: ['مدرجات 200 متفرج', 'غرف تبديل ملابس', 'مشروبات ومياه غازية'],
    badgeEn: 'Best 7v7 in Assiut',
    badgeAr: 'ملعب سباعي ممتاز بأسيوط',
    availableSlotAr: '09:30 م شاغر',
    availableSlots: ['4:00 PM', '5:30 PM', '7:00 PM', '8:30 PM'],
  },
  {
    id: 'court-5',
    nameEn: 'Minya Padel & Football Hub',
    nameAr: 'مجمع المنيا للباديل وكرة القدم',
    cityId: 'minya',
    sportType: 'padel',
    locationEn: 'Corniche El-Nile, Minya',
    locationAr: 'المنيا • كورنيش النيل الرئيسي',
    rating: 4.9,
    reviewsCount: 165,
    pricePerHour: 300,
    type: 'padel',
    typeEn: 'Indoor AC Padel & Turf',
    typeAr: 'مغطى ومكيف باديل وخماسي',
    surfaceEn: 'Professional Green Turf',
    surfaceAr: 'نجيل أخضر معتمد احترافي',
    image: 'https://images.unsplash.com/photo-1511988617509-a57c8a288659?auto=format&fit=crop&q=80&w=1000',
    facilities: ['Indoor AC', 'Pro Shop', 'Juice Bar'],
    facilitiesAr: ['تكييف مركزي', 'متجر أدوات ومضارب', 'بار عصائر طازجة'],
    badgeEn: 'Multi-Sport Hub',
    badgeAr: 'مجمع باديل وخماسي بالمنيا',
    availableSlotAr: '08:00 م شاغر',
    availableSlots: ['6:00 PM', '7:30 PM', '9:00 PM', '10:30 PM'],
  },
  {
    id: 'court-6',
    nameEn: 'Royal Padel & Football Qena',
    nameAr: 'رويال بادل وخماسي قنا',
    cityId: 'qena',
    sportType: 'football',
    locationEn: 'Stadium Area, Qena City',
    locationAr: 'قنا • منطقة الاستاد الرياضي',
    rating: 5.0,
    reviewsCount: 145,
    pricePerHour: 260,
    type: 'football',
    typeEn: 'Panoramic Turf 5v5',
    typeAr: 'خماسي نجيل بانورامي',
    surfaceEn: 'Premium Green Turf',
    surfaceAr: 'نجيل أخضر فاخر',
    image: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?auto=format&fit=crop&q=80&w=1000',
    facilities: ['Lounge', 'Energy Drinks', 'Pro Gear'],
    facilitiesAr: ['استراحة فاخرة', 'مشروبات طاقة', 'كرات رسمية معتمدة'],
    badgeEn: 'Top Rated in Qena',
    badgeAr: 'تقييم ممتاز بقنا',
    availableSlotAr: '09:00 م شاغر',
    availableSlots: ['5:30 PM', '7:00 PM', '8:30 PM', '10:00 PM'],
  },
];

export const DEMO_MATCHES = [
  {
    id: 'match-1',
    clubEn: 'Padel Square - Assiut',
    clubAr: 'بادل سكوير - أسيوط',
    dateEn: 'Today, 20:00 - 21:30',
    dateAr: 'اليوم، ٨:٠٠ م - ٩:٣٠ م',
    neededPlayers: 1,
    levelEn: 'Intermediate (C+ / B)',
    levelAr: 'متوسط (C+ / B)',
    pricePerPerson: 90,
    hostName: 'Mahmoud El-Assiuti',
    hostAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    hostRating: '4.9 ★',
    courtTypeEn: 'Outdoor Blue WPT Padel',
    courtTypeAr: 'باديل خارجي أزرق WPT',
  },
];

export const DEMO_TOURNAMENTS = [
  {
    id: 'tourney-1',
    titleEn: 'Upper Egypt Padel & Football League 2026',
    titleAr: 'دوري الصعيد للباديل وكرة القدم ٢٠٢٦',
    categoryEn: 'Pro Category (Assiut & Sohag)',
    categoryAr: 'فئة الأندية والمحترفين (أسيوط وسوهاج)',
    prizePool: '100,000 EGP',
    dateEn: 'Nov 01 - Nov 05, 2026',
    dateAr: '١ - ٥ نوفمبر ٢٠٢٦',
    locationEn: 'Nile Stadium Arena, Assiut',
    locationAr: 'ستاد النيل الرياضي، أسيوط',
    registeredTeams: 24,
    maxTeams: 32,
    image: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&q=80&w=1000',
    badgeEn: 'Registration Open',
    badgeAr: 'التسجيل مفتوح',
  },
];

export const DEMO_PACKAGES = [
  {
    id: 'pkg-1',
    nameEn: 'Upper Egypt Sports Pass 10-Sessions',
    nameAr: 'اشتراك الصعيد ١٠ مباريات (باديل وخماسي)',
    sessionsEn: '10 Court Hours + Peak Priority',
    sessionsAr: '١٠ ساعات حجز (باديل أو كرة قدم) + أولوية المواعيد',
    price: 2500,
    originalPrice: 3200,
    periodEn: '/ 10 Passes',
    periodAr: '/ ١٠ حصص حجز',
    featuresEn: ['20% Discount on hourly rates', 'Priority weekend slot locking', 'Free ball & gear provided'],
    featuresAr: ['خصم ٢٠٪ على سعر الساعة', 'أولوية حجز الويك إند بالصعيد', 'علبة كرات وتأجير مجاني'],
    recommended: true,
  },
];

export const PLATFORM_STATS = [
  { id: 'stat-1', value: 28, prefix: '+', suffix: '', num: '+28', progress: 88, growthAr: '+18% شهرياً', growthEn: '+18% MoM', labelEn: 'Padel & Football Courts', labelAr: 'ملعب  ' },
  { id: 'stat-2', value: 5, prefix: '+', suffix: 'K', num: '+5K', progress: 92, growthAr: '+24% أسبوعياً', growthEn: '+24% WoW', labelEn: 'Active Local Players', labelAr: 'لاعب  ' },
  { id: 'stat-3', value: 99, prefix: '', suffix: '%', num: '99%', progress: 99, growthAr: 'دقة 100%', growthEn: '100% On-time', labelEn: 'Time Slot Accuracy', labelAr: 'دقة المواعيد بالملاعب' },
  { id: 'stat-4', value: 12, prefix: '+', suffix: 'K', num: '+12K', progress: 95, growthAr: '+35% بطولات', growthEn: '+35% Tournaments', labelEn: 'Hours Booked', labelAr: 'ساعة محجوزة بالصعيد' },
];

export const DEMO_TESTIMONIALS = [
  {
    id: 'test-1',
    nameEn: 'Mahmoud El-Assiuti',
    nameAr: 'محمود الأسيوطي',
    roleEn: 'Padel Player • Assiut',
    roleAr: 'لاعب باديل • أسيوط',
    username: '@m_assiuti',
    commentEn: 'Finally a platform that covers Assiut & Sohag! Booking padel & 5v5 football courts used to take endless calls. Now we reserve in 10 seconds with instant confirmation.',
    commentAr: 'أخيراً منصة غطت أسيوط وسوهاج والصعيد بجد! كنا بنعاني عشان نلاقي مواعيد فاضية لملاعب البادل والخماسي. دلوقتي بنحجز في ١٠ ثواني والماتش بيبقى ميتأكد بالدقيقة.',
    rating: 5,
    avatarLetter: 'م',
    avatarBg: 'bg-[#CFF40E] text-[#010A1A]',
  },
  {
    id: 'test-2',
    nameEn: 'Hassan Sohati',
    nameAr: 'حسن السوهاجي',
    roleEn: 'Football Captain • Sohag',
    roleAr: 'كابتن فريق خماسي • سوهاج',
    username: '@h_sohagi',
    commentEn: 'The best booking app for 5v5 turf fields in Sohag! Instant time slots, exact location, and zero delays for our evening matches.',
    commentAr: 'أحسن أبلكيشن لحجز ملاعب الكورة الخماسي بسوهاج، بيورينا المواعيد الفاضية والإضاءة والملاعب الهولندية الممتازة وبنحجز الماتش من غير أي تأخير.',
    rating: 5,
    avatarLetter: 'ح',
    avatarBg: 'bg-[#0A58CA] text-white',
  },
  {
    id: 'test-3',
    nameEn: 'Eng. Mostafa Barakat',
    nameAr: 'م. مصطفى بركات',
    roleEn: 'Owner of Arena Assiut',
    roleAr: 'مالك ملاعب البادل والنجيل بأسيوط',
    username: '@m_barakat',
    commentEn: 'As a venue owner in Upper Egypt, the platform organized 100% of our daily schedules and eliminated no-shows completely.',
    commentAr: 'كصاحب ملاعب باديل وكرة قدم بأسيوط، المنصة نظمت الإشغال 100% وقضت تماماً على الحجوزات الوهمية، والإقبال على حجز البادل والخماسي بقى في التوب!',
    rating: 5,
    avatarLetter: 'م',
    avatarBg: 'bg-[#04307C] text-white',
  },
  {
    id: 'test-4',
    nameEn: 'Tarek El-Minyaawi',
    nameAr: 'طارق المنيوي',
    roleEn: 'Weekly Player • Minya',
    roleAr: 'لاعب أسبوعي • المنيا',
    username: '@tarek_minya',
    commentEn: 'Clean interface, fast confirmation, and very reliable for locking our Friday padel slots along Minya Corniche.',
    commentAr: 'واجهة سلسة جداً وتأكيد فوري، المنصة وفرت علينا مكالمات كتير وسهلت حجز ماتش الجمعة بكورنيش المنيا.',
    rating: 5,
    avatarLetter: 'ط',
    avatarBg: 'bg-[#CFF40E] text-[#010A1A]',
  },
  {
    id: 'test-5',
    nameEn: 'Captain Omar Qenawi',
    nameAr: 'كابتن عمر القناوي',
    roleEn: 'Tournament Organizer • Qena',
    roleAr: 'منظم بطولات خماسي • قنا',
    username: '@omar_qena',
    commentEn: 'Organizing 7v7 and 5v5 tournaments in Qena became 10x smoother. Player payments and schedule tracking work flawlessly.',
    commentAr: 'تنظيم بطولات الخماسي والسباعي بقنا بقى أسهل 10 مرات، دفع اللاعبين ومتابعة المواعيد شغالة بدقة ممتازة.',
    rating: 5,
    avatarLetter: 'ع',
    avatarBg: 'bg-[#0A58CA] text-white',
  },
  {
    id: 'test-6',
    nameEn: 'Dr. Ziad Aswan',
    nameAr: 'د. زياد الأسطواني',
    roleEn: 'Padel Enthusiast • Aswan',
    roleAr: 'ممارس باديل • أسوان',
    username: '@ziad_aswan',
    commentEn: 'Great experience! Love the real-time slot selection and instant SMS match notification for courts in Aswan.',
    commentAr: 'تجربة ممتازة! إشغال الملاعب ومواعيد الحجز واضحة بالدقيقة في أسوان، والتأكيد يوصل فوري رسالة على الموبايل.',
    rating: 5,
    avatarLetter: 'ز',
    avatarBg: 'bg-[#04307C] text-white',
  },
];
